apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adminer
  template:
    metadata:
      labels:
        app: adminer
    spec:
      containers:
      - name: adminer
        image: adminer:latest
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5 # Perbaikan typo: 'initalDelaySeconds' menjadi 'initialDelaySeconds'
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        volumeMounts: # <-- Tambahan ini
        - name: upload-storage
          mountPath: /var/www/html/uploads # Contoh path. Sesuaikan dengan kebutuhan Adminer atau aplikasi Anda.
          # readOnly: false # Opsional: Setel ke true jika hanya untuk membaca
      volumes: # <-- Tambahan ini
      - name: upload-storage
        persistentVolumeClaim:
          claimName: upload-pvc # Pastikan PVC ini sudah ada